apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vehicle-events-pg
  namespace: apps
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  storage:
    size: 0.5Gi
    storageClass: hostpath